server:
  port: 8081

spring:
  application:
    name: spring-ai-mcp-demo
  ai:
    openai:
      api-key: ${openrouter.api.key}
      base-url: ${openrouter.api.base-url}
      chat:
        options:
          model: ${openrouter.api.model}
    mcp:
      client:
        name: mcp-client
        version: 1.0.0
        enabled: true
        request-timeout: 10s
        type: SYNC
        stdio:
          connections:
            report:
              command: java
              args:
                - -jar
                - D:\project\spring-ai-demo\report-mcp\target\report-mcp-1.0-SNAPSHOT-jar-with-dependencies.jar
                - --mode=stdio
              env:
                PROJECT_PATH: D:/project/ccts-back
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6xqh51yf05318424o.mysql.rds.aliyuncs.com:3306/ccts-dev?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ccts!@#123
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


# OpenRouter API配置
openrouter:
  api:
    key: "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"
    base-url: https://openrouter.ai/api
    #model: tngtech/deepseek-r1t2-chimera:free
    #model: deepseek/deepseek-r1-0528-qwen3-8b:free
    model: moonshotai/kimi-k2:free

# DeepSeek API配置（备用）
deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    base-url: https://api.deepseek.com
    # V3模型 便宜
    model: deepseek-chat
    # R1模型 贵
    #model: deepseek-reasoner
# 阿里百炼平台
alibaba:
  api:
    key: ${QWEN_API_KEY}
    base-url: https://dashscope.aliyuncs.com/compatible-mode
    model: qwen-plus

logging:
  level:
    org.agent: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用配置
app:
  git:
    repository-path: D:/project/ccts-back  # Git仓库路径，可通过环境变量设置
  daily-report:
    default-days: 5  # 默认查询天数
    cache-hours: 24  # 缓存时间（小时）

