server:
  port: 8081

spring:
  application:
    name: spring-ai-mcp-demo
  redis:
    host: localhost
    port: 6379
  ai:
    openai:
      api-key: ${deepseek.api.key}
      base-url: ${deepseek.api.base-url}
      chat:
        options:
          model: ${deepseek.api.model}
      embedding:
        options:
          model: text-embedding-v4
    mcp:
      client:
        enabled: false
        name: mcp-client
        version: 1.0.0
        request-timeout: 10s
        type: SYNC
        stdio:
          connections:
            report:
              command: java
              args:
                - -jar
                - "D:/project/spring-ai-demo/report-mcp/target/report-mcp-1.0-SNAPSHOT.jar"
              env:
                PROJECT_PATH: D:/project/ccts-back


# OpenRouter API配置
openrouter:
  api:
    key: ${OPENROUTER_API_KEY:111}
    base-url: https://openrouter.ai/api
    #model: tngtech/deepseek-r1t2-chimera:free
    #model: deepseek/deepseek-r1-0528-qwen3-8b:free
    model: moonshotai/kimi-k2:free

# DeepSeek API配置（备用）  暂不支持RAG
deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    base-url: https://api.deepseek.com
    # V3模型 便宜
    model: deepseek-chat
    # R1模型 贵
    #model: deepseek-reasoner
# 阿里百炼平台
alibaba:
  api:
    key: ${QWEN_API_KEY}
    base-url: https://dashscope.aliyuncs.com/compatible-mode
    #model: qwen-plus
    model: qwen-max

logging:
  level:
    org.agent: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用配置
app:
  git:
    repository-path: D:/project/ccts-back  # Git仓库路径，可通过环境变量设置
  daily-report:
    default-days: 5  # 默认查询天数
    cache-hours: 24  # 缓存时间（小时）

