spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        enabled: true
        name: report-server
        version: 1.0.0
        stdio: true
        type: SYNC

logging:
  pattern:
    console:
